% % grid
% set(gca,                ...
%     'XGrid',        'on',...
%     'YGrid',        'on',...
%     'ZGrid',        'on');

% limit
set(gca,                ...
    'Xlim',        [-0.5,0.5],...
    'Ylim',       [-0.5,0.5],...
    'Zlim',       [0,1],...
    'DataAspectRatio', [1,1,1]);

set(gca,                ...
    'Box',        'on',...
    'BoxStyle',      'back');
set(gca,                ...
    'XTickLabelRotation', 0,...
    'YTickLabelRotation', 0,...
    'ZTickLabelRotation', 0);
set(gca,                ...
    'View',        [65,30]);

set(gca,                ...
    'LineWidth',       1);
% font
set(gca,                ...
    'FontWeight',       'bold');

set(gca,                ...
    'XTick',            [-0.5 -0.25 0 0.25 0.5],...
    'YTick',            [-0.5 -0.25 0 0.25 0.5],...
    'ZTick',            [0 0.25 0.5 0.75 1]);
% set(gca,                ...
%      'XTick',            [-50 -25 0 25 50],...
%      'YTick',            [-50 -25 0 25 50],...
%      'ZTick',            [0 25 50 75 100]);