% grid
set(gca,                ...
    'XGrid',        'on',...
    'YGrid',        'on',...
    'ZGrid',        'on');

% limit
set(gca,                ...
    'Xlim',        [-0.5,0.5],...
    'Ylim',       [-0.5,0.5],...
    'Zlim',       [0,1],...
    'DataAspectRatio', [1,1,1]);



set(gca,                ...
    'View',        [45,45]);