% hXLabel=xlabel('x (m)');
% hYLabel=ylabel('y (m)');
% hZLabel=zlabel('z (m)');
% set([hXLabel, hYLabel, hZLabel]  ,...
%     'FontSize'   , 12);
hXLabel=get(gca,'XLabel');
hYLabel=get(gca,'YLabel');
hZLabel=get(gca,'ZLabel');

set(hXLabel,        ...
    'String',      'x (m)',...
    'FontSize'   , 12);

set(hYLabel,        ...
    'String',      'y (m)',...
    'FontSize'   , 12);

set(hZLabel,        ...
    'String',      'z (m)',...
    'FontSize'   , 12);